version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: myWalletDb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - fashion-blog-pg-data:/var/lib/postgresql/data/fashionBlog
    ports:
      - "5435:5432"
    networks:
      - postgres-con
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  server:
    build:
      context: .
    container_name: decapay_server
    image: austinuc/fashion-blog
    environment:
      POSTGRES_HOST: decapay_db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - postgres-con


volumes:
  fashion-blog-pg-data:


networks:
  postgres-con: